### ISSUE TITLE
Cannot read data with 1D timeframe

### ISSUE THREAD

**Issue by dakimura** [alpacahq/marketstore#230]
On the current master branch, I cannot read data written with 1D timeframe.
After I write some data (ex. TEST/1D/OHLCV ), I can see ./data/TEST/1D/OHLCV directory and a data file like 2019.bin are created, and it seems the data binary is correctly written.

But when I query the data, `No files returned from query parse` is returned.
Please let me know if you have any thoughts on this.

```
#!/usr/bin/python
#-*- coding:utf-8 -*-

import numpy as np
import pandas as pd
import pymarketstore as pymkts

data = np.array([(pd.Timestamp('2017-01-01 00:00').value / 10**9, 10.0)], dtype=[('Epoch', 'i8'), ('Ask', 'f4')])
cli = pymkts.Client()
cli.write(data, 'TEST/1D/OHLCV')

print(cli.query(pymkts.Params('TEST', '1D', 'OHLCV')).first().df())
```
↓
```
Traceback (most recent call last):
  File "test_read.py", line 12, in <module>
    print(cli.query(pymkts.Params('TEST', '1D', 'OHLCV')).first().df())
  File "/Users/dakimura/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pymarketstore/client.py", line 96, in query
    reply = self._request('DataService.Query', **query)
  File "/Users/dakimura/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pymarketstore/client.py", line 87, in _request
    return self.rpc.response(rpc_reply)
  File "/Users/dakimura/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pymarketstore/jsonrpc.py", line 48, in response
    str(resp['error'].get('data', ''))))
Exception: No files returned from query parse, DataDir: Node: ., Category: Symbol, Subdirs: TEST:
None
```

**Comment by eli-kaplan** [comment]
Can confirm, having the same issue. I have back-filled data for various symbols off Polygon and aggregated the 1Min candles into 1H, 12H, and 1D. However, it seems that any time above 1H is inaccessible - the API always returns "No files returned from query parse." All of the files for times above 1H are present on-disk, and seem to be properly formatted.

**Comment by xgdgsc** [comment]
I get empty results with OHLCV instead of the error.
