### ISSUE TITLE
got error with binancefeeder 

### ISSUE THREAD

**Issue by alexcrownjr** [alpacahq/marketstore#293]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f9631a778a6]

goroutine 170 [running]:
github.com/alpacahq/marketstore/contrib/binancefeeder.(*BinanceFetcher).Run(0xc4212a6120)
	/go/src/github.com/alpacahq/marketstore/contrib/binancefeeder/binancefeeder.go:244 +0x216
created by github.com/alpacahq/marketstore/cmd/start.RunBgWorkers
	/go/src/github.com/alpacahq/marketstore/cmd/start/plugins.go:53 +0x1e2

my config file:
root_directory: data
listen_port: 5993
log_level: debug
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
stale_threshold: 5
enable_add: true
enable_remove: false
enable_last_known: true
bgworkers:
  - module: binancefeeder.so
    name: BinanceFetcher
    config:
      symbols:
      base_timeframe: "1min"
      base_currency: "BTC"
      query_start: "2020-01-01 00:00"

**Comment by alexcrownjr** [comment]
my bad - should be base_timeframe: "1Min" not "1min"
