### ISSUE TITLE
Panic on catalog initilization

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/marketstore#63]
I ran the latest code on my mac with gdax fetcher and right after startup panic'ed.

```
runtime: bad pointer in frame runtime.mapassign_faststr at 0xc42008b440: 0x30
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw(0x821ca81, 0x1e)
	/Users/hitoshi/local/go/src/runtime/panic.go:616 +0x81 fp=0x70000ae26708 sp=0x70000ae266e8 pc=0x7e750d1
runtime.adjustpointers(0xc42008b438, 0x70000ae26800, 0x70000ae26bc0, 0x8292dc0, 0x83ce4c0)
	/Users/hitoshi/local/go/src/runtime/stack.go:592 +0x23e fp=0x70000ae26778 sp=0x70000ae26708 pc=0x7e8abfe
runtime.adjustframe(0x70000ae26ad0, 0x70000ae26bc0, 0x83ce4c0)
	/Users/hitoshi/local/go/src/runtime/stack.go:663 +0x325 fp=0x70000ae26830 sp=0x70000ae26778 pc=0x7e8af45
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc420aa8780, 0x0, 0x0, 0x7fffffff, 0x822add8, 0x70000ae26bc0, 0x0, ...)
	/Users/hitoshi/local/go/src/runtime/traceback.go:310 +0x12d3 fp=0x70000ae26b38 sp=0x70000ae26830 pc=0x7e94093
runtime.copystack(0xc420aa8780, 0x2000, 0x70000ae26d01)
	/Users/hitoshi/local/go/src/runtime/stack.go:891 +0x26e fp=0x70000ae26cf0 sp=0x70000ae26b38 pc=0x7e8ba2e
runtime.newstack()
	/Users/hitoshi/local/go/src/runtime/stack.go:1063 +0x310 fp=0x70000ae26e80 sp=0x70000ae26cf0 pc=0x7e8be40
runtime.morestack()
	/Users/hitoshi/local/go/src/runtime/asm_amd64.s:480 +0x89 fp=0x70000ae26e88 sp=0x70000ae26e80 pc=0x7e9a1a9

goroutine 66 [copystack]:
runtime.(*mcache).nextFree(0x50746c8, 0x16, 0x0, 0x0, 0x0)
	/Users/hitoshi/local/go/src/runtime/malloc.go:545 +0x254 fp=0xc42008b318 sp=0xc42008b310 pc=0x7e5bef4
runtime.mallocgc(0xa0, 0x4634100, 0x1, 0xc420077470)
	/Users/hitoshi/local/go/src/runtime/malloc.go:710 +0x7e5 fp=0xc42008b3b8 sp=0xc42008b318 pc=0x7e5c6e5
runtime.newobject(0x4634100, 0xe0209b03)
	/Users/hitoshi/local/go/src/runtime/malloc.go:839 +0x38 fp=0xc42008b3e8 sp=0xc42008b3b8 pc=0x7e5ca98
runtime.mapassign_faststr(0x45f0e00, 0xc42026ce40, 0x0, 0x0, 0xc420077498)
	/Users/hitoshi/local/go/src/runtime/hashmap_fast.go:712 +0x383 fp=0xc42008b458 sp=0xc42008b3e8 pc=0x7e57f03
github.com/alpacahq/marketstore/catalog.(*Directory).gatherCategoriesUpdateCache.func1(0xc4202c6000, 0x45f0e00, 0xc42026ce40)
	/Users/hitoshi/alpaca/go/src/github.com/alpacahq/marketstore/catalog/catalog.go:458 +0x58 fp=0xc42008b490 sp=0xc42008b458 pc=0x7fb1c68
github.com/alpacahq/marketstore/catalog.(*Directory).recurse(0xc4202c6000, 0x45f0e00, 0xc42026ce40, 0x822a8d8)
	/Users/hitoshi/alpaca/go/src/github.com/alpacahq/marketstore/catalog/catalog.go:543 +0xa2 fp=0xc42008b520 sp=0xc42008b490 pc=0x7fb06a2
github.com/alpacahq/marketstore/catalog.(*Directory).gatherCategoriesUpdateCache(0xc4202c6000, 0x10)
	/Users/hitoshi/alpaca/go/src/github.com/alpacahq/marketstore/catalog/catalog.go:461 +0x5a fp=0xc42008b558 sp=0xc42008b520 pc=0x7faff9a
github.com/alpacahq/marketstore/catalog.(*Directory).GatherCategoriesFromCache(0xc4202c6000, 0x10)
	/Users/hitoshi/alpaca/go/src/github.com/alpacahq/marketstore/catalog/catalog.go:384 +0x6b fp=0xc42008b580 sp=0xc42008b558 pc=0x7fafc1b
github.com/alpacahq/marketstore/planner.(*query).Parse(0xc421370000, 0xc42024d2a8, 0x7fffffffffffffff, 0x4cb6be0)
	/Users/hitoshi/alpaca/go/src/github.com/alpacahq/marketstore/planner/planner.go:236 +0x47 fp=0xc42008b718 sp=0xc42008b580 pc=0x7fb49c7
github.com/alpacahq/marketstore/contrib/gdaxfeeder.findLastTimestamp(0x82140a9, 0x3, 0xc420250050, 0x0, 0x0, 0xc420250050)
	/Users/hitoshi/alpaca/go/src/github.com/alpacahq/marketstore/contrib/gdaxfeeder/gdaxfeeder.go:99 +0x214 fp=0xc42008b7b8 sp=0xc42008b718 pc=0x813f744
github.com/alpacahq/marketstore/contrib/gdaxfeeder.(*GdaxFetcher).Run(0xc4202d4480)
	/Users/hitoshi/alpaca/go/src/github.com/alpacahq/marketstore/contrib/gdaxfeeder/gdaxfeeder.go:122 +0x2ce fp=0xc42008bfd8 sp=0xc42008b7b8 pc=0x813fb6e
runtime.goexit()
	/Users/hitoshi/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42008bfe0 sp=0xc42008bfd8 pc=0x4059a81
created by main.RunBgWorkers
	/Users/hitoshi/alpaca/go/src/github.com/alpacahq/marketstore/cmd/marketstore/plugins.go:52 +0x1ef
```

The relevant code is here.

```
func (d *Directory) gatherCategoriesUpdateCache() map[string]int8 {
	// Must be thread-safe for WRITE access
	// Note that this should be called whenever catalog structure is modified to update the cache
	catListFunc := func(d *Directory, i_list interface{}) {
		list := i_list.(map[string]int8)
		list[d.category] = 0
	}
	newCatList := make(map[string]int8, 0)
	d.recurse(newCatList, catListFunc)
	d.Lock()
	d.catList = newCatList
	d.Unlock()
	return newCatList
}
```

It looks to me `d.recurse` should also be protected by the write lock, since `d.category` may be changed by someone else.

**Comment by umitanuki** [comment]
Actually it's not about concurrency, but rather likely Go's plugin issue on Mac.  Similar to this. https://github.com/golang/go/issues/24351

**Comment by umitanuki** [comment]
Go 1.10.2 Mac

**Comment by Darkbladecr** [comment]
Same issue with `go version go1.10.3 darwin/amd64`

**Comment by umitanuki** [comment]
good to know
